version: '3.8'
services:
  db:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env
  bot:
    build: 
      context: .
    command: ["python", "-m", "bot"]
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  mongodb-data: